COORDINATOR_ADDRESS = 'localhost'
COORDINATOR_PORT = 6789
REPLICATION_SERVER_1_ADDRESS = 'localhost'
REPLICATION_SERVER_1_PORT = 6790
REPLICATION_SERVER_2_ADDRESS = 'localhost'
REPLICATION_SERVER_2_PORT = 6791
